### ISSUE TITLE
(SIGNUP) Usuarios con mismo nombre / aplica tambien a e-mail 

### ISSUE THREAD

**Issue by Mapach3** [andresfiloso/Revision-Sistematica#2]
Los nombres de usuario no son unívocos para cada uno, es decir que dos usuarios (o más) pueden tener el mismo nombre de usuario cuando se registran en el sistema.
Sucede lo mismo con los e-mail, dos usuarios pueden registrarse con el mismo e-mail

**Comment by andresfiloso** [comment]
Resuelto. Por favor, testear devuelta y agregar a pruebas.  Gracias @Mapach3
