### ISSUE TITLE
(FIRSTPROJECT) Chequear nombre antes de pasar al modulo?

### ISSUE THREAD

**Issue by Mapach3** [andresfiloso/Revision-Sistematica#3]
El nombre del primer proyecto se pone en la pantalla "projects", y despues con ese nombre se pasa a "firstProject" a poner el resto de los datos. Habría que chequear que no permita ingresar caracteres inválidos en esa etapa para evitar errores a futuro.

**Comment by andresfiloso** [comment]
Resuelto. En anteriores commits se genero el método validCharacters() el cual fue utillizado para resolver esta issue. Gracias @Mapach3
