### ISSUE TITLE
(LOOKUP) Fallan modulos de exclude e include

### ISSUE THREAD

**Issue by Mapach3** [andresfiloso/Revision-Sistematica#5]
Los módulos para incluir y excluir términos funcionan únicamente en la primera búsqueda. Cuando se agrega una secundaria o posteriores no hacen nada.

**Comment by andresfiloso** [comment]
Ahí tendría que funcionar bien. No lo pude probar a fondo. Quizás le podes encontrar algún otro bug mas. En ese caso, reabrí la issue.
