### ISSUE TITLE
(LOOKUP) Busquedas conectadas con AND?

### ISSUE THREAD

**Issue by Mapach3** [andresfiloso/Revision-Sistematica#6]
Cuando se agrega una segunda busqueda o posteriores además de la principal, las querys son conectadas por un AND. No deberían ser conectadas con un OR?

**Comment by andresfiloso** [comment]
### Tipos de búsqueda: 
**Búsqueda simple:** Incluye únicamente una búsqueda. La misma puede contener operadores lógicos (AND, AND NOT, OR)
**Búsqueda paralela:** Incluye 2 o más búsquedas las cuales se realizan de forma paralela para lograr resultados mas específicos. La misma puede contener operadores lógicos (AND, AND NOT, OR)

**Ejemplo con 2 busquedas:**

• **Búsqueda 1:** Big data AND Data Science
• **Búsqueda 2:** Model AND Arquitecture

**query:** `Big data AND Data Science AND Model OR Big data AND Data Science AND Architecture`

**Ejemplo con 3 búsquedas:**

• **Búsqueda 1:** Big data AND Data Science
• **Búsqueda 2:** Model AND Arquitecture
• **Busqueda 3:** 2017 AND 2018

**query:**  `Big data AND Data Science AND Model AND 2017 OR Big data AND Data Science AND Model AND 2018 OR Big data AND Data Science AND Architecture AND 2017 OR Big data AND Data Science AND Architecture AND 2018​​`

**Comment by Mapach3** [comment]
Cierro ya que se trataba de una duda personal acerca de como se realizaba la query
