### ISSUE TITLE
(GENERAL) Limitar inputs a solo palabras

### ISSUE THREAD

**Issue by Mapach3** [andresfiloso/Revision-Sistematica#7]
El problema general con todos los inputs es que cuando se ponen caracteres como '|¿??? se suele romper el sistema tirando un error de sqlite.
Hay que limitar todos los inputs para que el usuario solamente pueda ingresar palabras y no caracteres extraños.

**Comment by andresfiloso** [comment]
Tal como se hizo en la issue #3, ¿Podrías hacer un listado de todos los inputs que están fallando y con que valor arrojan error? Ya estoy corrigiendo los que encuentro, pero quiero tener una lista de donde probar, para no abrir la issue devuelta o que abrirla de nuevo sea a causa de un input que no encontraste. Podrías también utilizar esta plantilla para especificar cada caso: 

```
URL: /projects
Referencia del componente: input para agregar colaborador
Texto testeado: '|¿???
Error: OperationalError: near "?": syntax error
```

Gracias!

**Comment by Mapach3** [comment]
Test_1
```
URL: /projects (se ingresa el nombre en esta url) /firstProject
Referencia del componente: input para determinar el nombre del primer proyecto
Texto testeado: ||||||||¿¿¿¿¿"""""???
Error: El proyecto pasa a tener un nombre blank:

(https://user-images.githubusercontent.com/31143445/49601544-dcb9a580-f964-11e8-8a63-476e8000a14e.png) 

(https://user-images.githubusercontent.com/31143445/49601605-096dbd00-f965-11e8-857a-4378381598fc.png)
```

Test_2
```
URL: /projects (se ingresa el nombre en esta URL) /firstProject
Referencia del componente: input para determinar el nombre del primer proyecto.
Texto testeado: |||||||||¿'¿'¿'¬¬¬¬?!?!?!?}}+´´´´´´{{{
Error: El nombre del proyecto pasa a ser --!!!}}+{{{-- , ya que el modulo borra los caracteres no permitidos
```

Test_3
```
URL:   /lookup (se ingresan los keyword en esta URL)   /scrapping (al realizar la busqueda)
Referencia del componente: input para realizar una busqueda
Texto testeado: ?????+|+|+|+|{|||||¿¿ AND data mining
Error: IOError: [Errno 2] No such file or directory: 'json_raws/?????+|+|+|+|{|||||\xc2\xbf\xc2\xbf AND data mining.json'
```

Test_4
```
URL: /lookup (se ingresan keywords en esta URL) /scrapping (al realizar la busqueda)
Referencia del componente: input para realizar una busqueda
Texto testeado: ||¿¿??'M" 
Error:   IOError: [Errno 2] No such file or directory: 'json_raws/||\xc2\xbf\xc2\xbf??\'M"  AND data.json'

```

**Comment by andresfiloso** [comment]
Perfecto. Una duda sobre la segunda prueba:

```
URL: /projects (se ingresa el nombre en esta URL) /firstProject
Referencia del componente: input para determinar el nombre del primer proyecto.
Texto testeado: |||||||||¿'¿'¿'¬¬¬¬?!?!?!?}}+´´´´´´{{{
Error: El nombre del proyecto pasa a ser --!!!}}+{{{-- , ya que el modulo borra los caracteres no permitidos
```

validCharacters() ya hace la validación es este caso y borra los caracteres no permitidos. **Decretemos que caracteres están o no permitidos**, porque en este caso el comportamiento sería el esperado.

```
def validCharacters(string):

	whitelist = set('abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890$%^&*()!#@-_+/%$.,:{;[]}')
	string = ''.join(filter(whitelist.__contains__, string))

	return string
```

donde:

`abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890$%^&*()!#@-_+/%$.,:{;[]}`

serían los **únicos caracteres permitidos**.

Dame el ok o agreguemos caracteres permitidos.

Saludos,

**Comment by andresfiloso** [comment]
Por ejemplo, ¬ podría ser un caracter aceptado, pero el signo de pregunta (?) no. Ahí va mi consulta. Decretemos cuales van y cuales no para hacer pruebas sobre eso y no volver a atrás.

**Comment by Mapach3** [comment]
Personalmente creo que la String que definiste estaría perfecta, aunque tengo dudas sobre algunos caracteres (% ^ & * y $ me asustan un poco).
Podemos dejarla así por el momento y después si hacemos pruebas y tiran error las sacamos? o si o si tenemos que definir en esta etapa cuales van a ser los permitidos?

**Comment by andresfiloso** [comment]
Si esta String no rompe en ningún lado y no estamos dejando ningún caracteres importante afuera, sigamos adelante. Si durante las pruebas, encontrás algún caracterer que no está incluido y es importante, generamos una nueva issue para agregar ese caracterer y posterior a eso deberíamos repetir las pruebas para asegurarnos que esa inserción no rompe en ningún lado. Por ese motivo, creo conveniente definir la String desde el inicio. En mi opinión, pienso que es una buena String, contempla casi todos los caracteres importantes y no debería traernos muchos problemas. Sigo adelante sin modificaciones sobre validCharacters() y desestimo la prueba 2 ya no hay bug ahí.

**Comment by andresfiloso** [comment]
### Solución issue #7
```
def validCharacters(string):

	whitelist = set('abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890$%^&*()!#@-_+/%$.,:{;[]}|?¬><~?><¿')
	string = ''.join(filter(whitelist.__contains__, string))

	return string
```
```
# A filename cannot contain any of the following characters: \ / : * ? " < > |
def validQuery(string):

	whitelist = set('abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890$%^&()!#@-_+%$.,{;[]}')
	string = ''.join(filter(whitelist.__contains__, string))

	return string

```
Test_1

```
URL: /projects (se ingresa el nombre en esta url) /firstProject
Referencia del componente: input para determinar el nombre del primer proyecto
Texto testeado: ||||||||¿¿¿¿¿"""""???
Resultado esperado: ||||||||???
Resultado obtenido: ||||||||???
Observaciones: validCharacters() elimina ¿ y "
```

Test_2

```
URL: /projects (se ingresa el nombre en esta URL) /firstProject
Referencia del componente: input para determinar el nombre del primer proyecto.
Texto testeado: |||||||||¿'¿'¿'¬¬¬¬?!?!?!?}}+´´´´´´{{{
Resultado esperado: |||||||||?!?!?!?}}+{{{
Resultado obtenido: |||||||||?!?!?!?}}+{{{
Observaciones: validCharacters() elimina ¿, ' y ´ 
```

Test_3

```
URL:   /lookup (se ingresan los keyword en esta URL)   /scrapping (al realizar la busqueda)
Referencia del componente: input para realizar una busqueda
Texto testeado: ?????+|+|+|+|{|||||¿¿ AND data mining
Resultado esperado: ++++{ AND data mining
Resultado obtenido: ++++{ AND data mining
Observaciones: Se genera metodo validQuery(), solo permite caracteres válidos para operaciones IO sobre archivos. Referencia a error "A filename cannot contain any of the following characters: \ / : * ? " < > |"
```

Test_4

```
URL: /lookup (se ingresan keywords en esta URL) /scrapping (al realizar la busqueda)
Referencia del componente: input para realizar una busqueda
Texto testeado: ||¿¿??'M" 
Resultado esperado: M
Resultado obtenido: M
Observaciones: Se genera metodo validQuery(), solo permite caracteres válidos para operaciones IO sobre archivos. Referencia a error "A filename cannot contain any of the following characters: \ / : * ? " < > |"
```

Gracias @Mapach3. Doy por cerrado el problema. Por favor, validar y documentar. En caso de volver a encontrar un error relacionado a este tema, abrir otra issue y hacer referencia a #7

**Comment by Mapach3** [comment]
Creo que haría falta agregar alguna leyenda para informarle al usuario que la búsqueda que realizó contenía valores inválidos, y que por esa razón se transformó en otra (para que esté al tanto de lo sucedido, porque a menos que este vea el Input, nunca es avisado).
